{
    'name': 'Clothes Store',
    'version': '15.0.1.0.0',
    'sequence': -1000,
    'description': """Clothes Store""",
    'category': 'Productivity',
    'website': '',
    'depends': [],
    'data': [
        'wizard/clothes_pay_wizard.xml',
        'views/clothes_root_menu.xml',
        'views/clothes_product_views.xml',
        'views/clothes_product_category_views.xml',
        'views/clothes_staff_views.xml',
        'views/clothes_customer_views.xml',
        'views/clothes_supplier_views.xml',
        'views/clothes_warehouse_views.xml',
        'views/clothes_import_product_views.xml',
        'views/clothes_bill.xml',
        'views/clothes_bill_details.xml',
        'views/clothes_category_views.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'report/bill_report_template.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}