from . import clothes_member
from . import clothes_supplier
from . import clothes_staff
from . import clothes_bill
from . import clothes_customer
from . import clothes_bill_details
from . import clothes_product
from . import clothes_product_category
from . import clothes_warehouse
from . import clothes_import_product
from . import clothes_category
